#
# This script make a validation using Fowlkes and Mallow Index
# to verify the clustering algorithm
#
# It compares clusters selecting pair of points
#
# We need a Ground Truth where each point has its classification (A real partition)
#
# In the partition generated by algorithm is the second partition
import os
import sys
import itertools


def validation(inputFile):

    if (inputFile == ""):
        return False, 0.0

    # replace "\\" by "/". In windows machines uses "\" for subdirectories. Python could handle with / in all OSs.
    #inputFile = inputFile.replace("\\", "/")

    # Create matMap list where there is the correspondence btw cluster number found and the ground truth

    fInd = open(inputFile, "r")
    #
    # matClusters is a list of points
    #    and each point has a list that defines the cluster label it belongs on Ground Truth partition (position 0) and
    #    gCluster partition (position 1)
    #
    matClusters = []
    first = True
    minCells = 0
    for line in fInd:
        CSVLine = line.split(",")
        if first:
            first = False
            continue
        aux = [int(CSVLine[-2]), int(CSVLine[-1])]
        matClusters.append(aux)

    #
    # Process to calculate index
    #
    # First create a combination of all points in matClusters
    #
    # for each pair of points, compare the cluster label of point in Ground Truth (position 0) and
    #          cluster label of point
    #
    # Calculate the classification of each pair of points
    #

    ss = 0
    sd = 0
    ds = 0
    dd = 0

    # Now iterate a combination of matClusters

    for pairs in itertools.combinations(matClusters, 2):
        # compare clusters on GT
        clGT = (pairs[0][1] == pairs[1][1])  # test clusters on GT
        clgC = (pairs[0][0] == pairs[1][0])  # test clusters no gCluster

        if (clgC and clGT):  # same cluster on gCluster and GT
            ss += 1
        elif (clgC and not clGT):  # same on gCluster and diff on GT
            sd += 1
        elif (not clgC and clGT):  # diff on gCluster and same on GT
            ds += 1
        else:  # diff clusters on both partitions
            dd += 1

    m1 = ss + sd
    m2 = ss + ds
    m = ss + sd + ds + dd

    # calculate FM index: ss over the square root of m1 x m2
    fm = ss / ( (m1 * m2) ** 0.5 )
    rand = (ss + sd) / m
    jac = (ss) /  (ss + sd + ds)

    return True, fm, rand, jac